### ISSUE TITLE
Github Topics

### ISSUE THREAD

**Issue by tinohager** [sonntagd/ZVT-experiments#1]
Can they still add Topics to their Github project so that you can find the projects on this topic better?

Topics:
zvt, zvt-protocol

**Comment by sonntagd** [comment]
Hi Tino, I'm not sure what you mean or what I should do for it?

**Comment by tinohager** [comment]
![image](https://user-images.githubusercontent.com/8215186/139601713-fa259886-01dd-485f-b650-12f456764e1e.png)

**Comment by sonntagd** [comment]
done :-)
